Reserve a top-level namespace 'contact-software'
CycloneDX/cyclonedx-property-taxonomy pull request #101
Opened 2024-09-24 10:28 UTC by wenns

closes https://github.com/CycloneDX/cyclonedx-property-taxonomy/issues/100

2024-09-24 10:43 UTC, jkowalleck requested changes

2024-09-24 10:43 UTC, jkowalleck commented on README.md
> -Namespaces are hierarchical and delimited with a ":".
this change was unintentional and must be reverted.

2024-09-24 10:43 UTC, jkowalleck commented on README.md
> -Regardless of other licensing attributes in this repository or document,
this change was unintentional and must be reverted.

2024-09-24 13:40 UTC, wenns commented on README.md
> -Namespaces are hierarchical and delimited with a ":".
Well, it was: I remoted trailing whitespace ;)
Same below. 

I can revert it, but I thought that you follow the "no trailing whitespace" convention?

2024-09-24 13:44 UTC, wenns commented on README.md
> -Namespaces are hierarchical and delimited with a ":".
Ah, I guess its the newline syntax in markdown... ?

2024-09-24 16:15 UTC, jkowalleck commented on README.md
> -Namespaces are hierarchical and delimited with a ":".
> I can revert it, but I thought that you follow the "no trailing whitespace" convention?


in markdown, 2 trailing white spaces are a line break.

2024-09-24 16:15 UTC, jkowalleck approved these changes

2024-09-24 16:16 UTC, merged

2024-09-24 16:17 UTC, jkowalleck commented
merged, namespace is reserved.

Please drop a pull request as soon as you have your taxonomy published.

2024-12-04 14:44 UTC, jkowalleck commented
hello @wenns , 

The reserved top level namespace `contact-software` exists for a while now, but the actual taxonomy was never linked here.
Could you check whether your taxonomy was published somewhere, and link it in the registry?