init `cdx:maven` taxonomy with existing properties
CycloneDX/cyclonedx-property-taxonomy pull request #69
Opened 2023-07-31 20:46 UTC by hboutemy

fixes #68 with existing properties added in cyclonedx-maven-plugin 2.7.7 and 2.7.9
once this is done, we'll add new properties later

2023-07-31 20:54 UTC, jkowalleck requested changes

2023-07-31 20:54 UTC, jkowalleck commented on cdx/maven.md
> +| `cdx:maven:package:scopes` | The activated Maven dependency scopes: `compile`, `provided`, `runtime`, `system` or `test`, comma-separated if many. |
> comma-separated if many.

that is a bad idea. instead of comma separated values use multi-appearance.



the CDXproperties are allowed to use the same hey multiple times with differnt values.  see <https://cyclonedx.org/use-cases/#properties--name-value-store>
This is why some taxonomies state one of these
- "May appear once"
- "May appear multiple times with different values"

2023-07-31 20:54 UTC, jkowalleck commented on cdx/maven.md
> +| `cdx:maven:package:reproducible` | Whether the SBOM has been generated in Reproducible Builds mode: in this mode, metadata timestamp and BOM serial number are dropped. _Boolean value_. If the prope
> _Boolean value_.

what are acceptable l9terals for boolean? are they case sensitive? 
baybe add something like here: https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/8bc7206058c8c0dea7e05bdf12d928877426b984/cdx/npm.md?plain=1#L8

2023-08-01 06:36 UTC, hboutemy commented on cdx/maven.md
> +| `cdx:maven:package:scopes` | The activated Maven dependency scopes: `compile`, `provided`, `runtime`, `system` or `test`, comma-separated if many. |
ok, I'll update to match this practice

2023-08-01 06:37 UTC, hboutemy commented on cdx/maven.md
> +| `cdx:maven:package:reproducible` | Whether the SBOM has been generated in Reproducible Builds mode: in this mode, metadata timestamp and BOM serial number are dropped. _Boolean value_. If the prope
ok, I'll add that

2023-08-02 06:30 UTC, hboutemy commented
thanks for the feedback: I improved the taxonomy

I have one question: I named the taxonomy `cdx:maven:package` to mimic other taxonomies in this repository, but wouldn't it be better named `cdx:maven:metadata` to match CycloneDX schema element?

2023-08-02 11:24 UTC, jkowalleck commented
re https://github.com/CycloneDX/cyclonedx-property-taxonomy/pull/69#issuecomment-1661578489

The `xxx:package:yyy` were chosen as the properties describe a package or component.
Looking into the details of your taxonomy description, I get the idea that your properties describe build processes or formulation, others describe the BOM generation process itself.
You probably want to rename the properties, so it is clear in which domain they shall be used and what they describe.

I am not familiar with maven dependency management, you should gather feedback from your peers :D 
Here are my 2 cents
- `cdx:maven:package:goal` -- this is not maven specific but implementation specific for [the](https://github.com/CycloneDX/cyclonedx-maven-plugin), i do not have any idea which category this might belong
- `cdx:maven:package:reproducible` -- is not maven specific. this could be a general `cdx:bom:reproducible` property. CC @stevespringett @CycloneDX/core-team 


I am not familiar with maven dependency management, you should gather feedback from your peers :D

2023-08-03 11:44 UTC, hboutemy commented
> The `xxx:package:yyy` were chosen as the properties describe a package or component.

this way of describing hides if the "package or component" is the output of the build or if it's a dependency (or even a tool)

> Looking into the details of your taxonomy description, I get the idea that your properties describe build processes or formulation, others describe the BOM generation process itself.

everything for the moment describes the BOM generation process itself, then it's natural that all go into one single namespace: FYI, here is the current cyclonedx-maven-plugin output gefore mugrating to the official taxonomy that this PR is trying to create https://gist.github.com/hboutemy/e9bed6b890e10450a8410f317e8d6e07

does it describe the package or something else, then how should it be named is my question: I did not try to execute other tools in other technologies to see where they used their `xxx:package:yyy` taxonomy

> cdx:maven:package:reproducible -- is not maven specific. this could be a general cdx:bom:reproducible property.

AFAIK, CycloneDX is inheritently against Reproducible Builds (because it expects the build timestamp to be stored): the feature is currently Maven specific, as if drops the usual timestamp

For now, I prefer keeping that Maven specific: we'll see later if moving to a more common taxonomy makes sense

2023-08-06 21:26 UTC, stevespringett commented
> AFAIK, CycloneDX is inheritently against Reproducible Builds (because it expects the build timestamp to be stored)

Timestamp is [required per NTIA Minimum Elements](https://www.ntia.doc.gov/sites/default/files/publications/sbom_minimum_elements_report_0.pdf). The team is not against reproducible builds, although they do very little to increase assurance, especially with Maven and similar ecosystems. This is being demoed at BlackHat this week. We should likely keep `reproducible ` out of Maven specifically and have it somewhere else thats common.

We should likely change the following:
```json
{
  "name" : "maven.scopes",
  "value" : "compile,provided,runtime,system"
}
```

to

```json
{
  "name" : "cdx:maven:package:scope",
  "value" : "compile"
}
{
  "name" : "cdx:maven:package:scope",
  "value" : "provided"
}
{
  "name" : "cdx:maven:package:scope",
  "value" : "runtime"
}
{
  "name" : "cdx:maven:package:scope",
  "value" : "system"
}
```

This would automatically form an array for many parsers and implementations would not have to parse `value` to separate out the scopes.

2023-08-07 10:50 UTC, jkowalleck commented
> We should likely keep reproducible out of Maven specifically and have it somewhere else thats common. 

let's have a boolean property `cdx:reproducible` in https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/main/cdx.md

2023-08-12 20:10 UTC, hboutemy commented
yes, `bom.metadata.properties` is where I store the fact that the BOM is expected to be reproducible

once the `cdx:reproducible` property will have been registered, I'll update this PR to drop the Maven-specific one

2023-08-13 07:51 UTC, jkowalleck commented
> yes, `bom.metadata.properties` is where I store the fact that the BOM is expected to be reproducible
> 
> once the `cdx:reproducible` property will have been registered, I'll update this PR to drop the Maven-specific one

see https://github.com/CycloneDX/cyclonedx-property-taxonomy/pull/70

2023-08-20 07:14 UTC, jkowalleck commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
Please help me understand: Would other tools that generate SBOMs from maven use these values, too?
- are these values well-known to maven?
- Is there maybe an online documentation for these values, so people know what they mean?

2023-08-20 07:14 UTC, jkowalleck commented on cdx/maven.md
> +| `cdx:maven:package:scope` | An activated Maven dependency scope: `compile`, `provided`, `runtime`, `system` or `test`. |
Could you link the docs? 

maybe like 
```patch
- | `cdx:maven:package:scope` | An activated Maven dependency scope: `compile`, `provided`, `runtime`, `system` or `test`. |
+ | `cdx:maven:package:scope` | An activated Maven [dependency scope]: `compile`, `provided`, `runtime`, `system` or `test`. |
```

and add at the bottom of the document:
```text

[dependency scope]: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

```

2023-08-21 22:41 UTC, hboutemy commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
this notion of goal is specific to Maven, and well known for any Maven user
the list of goals is in plugins' documentation https://github.com/CycloneDX/cyclonedx-maven-plugin#goals 
I'm not convinced adding a link gives great value, but I can add it to the "goal" term in the sentence

2023-08-21 22:49 UTC, hboutemy commented on cdx/maven.md
> +| `cdx:maven:package:scope` | An activated Maven dependency scope: `compile`, `provided`, `runtime`, `system` or `test`. |
done in c9aac68

2023-08-22 05:55 UTC, jkowalleck commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
> I'm not convinced adding a link gives great value, but I can add it to the "goal" term in the sentence

it does. A SecOps person might not know any maven nor java, but they know SBOM and they would want to know what this value means and where to read about it, so they can judge the value of an SBOM.

> [...] well known for any Maven user

for ANY user? Or maybe only for users of `cyclonedx-maven-plugin`, since these goals are only available when this plugin is used? 
I was unable to find anything regarding these goals/values, outside the context of cyclonedx-maven-plugin`. 
I am not convinced that this property is global/broad enough. I still think it is specific for `cyclonedx-maven-plugin`, and other SBOM tools would not use it nor recognize it at all. Could you help me understand why I am wrong?

2023-08-22 06:33 UTC, hboutemy commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
you're right, I over-focused on SBOM producer, who is a Maven user, knowing Maven concepts and how to look for this plugin specific details that match usual Maven concepts
but SBOM is much about consumers, and here, the diversity in culture is really wide
Notice that without waiting, I already added the documentation on goals while doing the suggested link to Maven scopes: it's easy to do and maintain, then it's worth the tiny effort :)

2023-08-22 06:43 UTC, jkowalleck commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
regarding SBOM generators: is this property specific to `cyclonedx-maven-plugin`?
In reverse: would other SBOM generators, like `trivy` or `cdxgen` also be able to use this property? 

If this property is only relevant for users of  `cyclonedx-maven-plugin`,
then you should document the property in the readme of `cyclonedx-maven-plugin`, not here.

2023-08-23 05:54 UTC, hboutemy commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
`goal` is really `cyclonedx-maven-plugin` specific
and it is documented in the plugin, I added a link, there is nothing more to document, the simple fact that a goal is used or another will fill the property without any possible customisation

2023-08-23 05:58 UTC, hboutemy commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
trying to put understanding in words: what seems logical is that
- documentation done here is for SBOM consumers, to understand the meaning of a property when they read a generated SBOM
- documentation in `cyclonedx-maven-plugin` is for SBOM producers, who can sometimes customize some fields in the SBOM generation

in this goal case, there is now a doc for consumers (here), and there is nothing to customise for SBOM producer: the property is just filled with what the producer used at Maven level when producing.

2023-08-23 06:19 UTC, jkowalleck commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
> `goal` is really `cyclonedx-maven-plugin` specific

So the property is implementation-centric to `cyclonedx-maven-plugin`. 
Then you should remove the property here. 
The properties documented are meet to be implementation-independent, ecosystem-oriented.

But I sense there is actually more to this property, some reasoning for having it here.
Therefore, here is what I _suspect_:
For you as an expert with maven, these different "goal" values imply a certain quality and other aspects to the BOM. But for me, "goal" is too specific to the implementation of `cyclonedx-maven-plugin`. Actually there might be a concept behind all this, that should be clarified.
Is it, that the goal actually indicates the general "scope" of the BOM document, whether it was generated for a "aggregation", a "package", or a "module"? For you, who has a deep understanding of maven and `cyclonedx-maven-plugin`, these "goal" values have meaning, and you want others to understand.

So maybe you could use a property `cdx:maven:sbom-scope` or something, with a set of well-defined values. Yes, you should have the values explained, what they mean.

2023-08-23 17:09 UTC, hboutemy commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
> The properties documented are meant to be implementation-independent, ecosystem-oriented.

given other pipenv and poetry existing taxonomies, I'm surprised: AFAIK, they share the same ecosystem, isn't it?

for npm, composer and maven, it's not clear if it's ecosystem names or build tool names (or even plugin-specific given some build tools won't have unique built-in SBM generation but feature provided by plugins)

but ok, in this case, `cdx:reproducible` was the only generic property: on the 3 remaining, 2 are Maven build tool specific, and the last one is really the only one that is strictly cyclonedx-maven-plugin specific

I'll drop this taxonomy and will continue to have non-standardized properties.

2023-08-24 06:59 UTC, jkowalleck commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
> given other pipenv and poetry existing taxonomies, I'm surprised: AFAIK, they share the same ecosystem, isn't it?

Most python-based ecosystem have https://pypi.org/ as a package source.
Pipenv and poetry have completely own wordings, definitions, workflows.

> for npm, composer and maven, it's not clear if it's ecosystem names or build tool names

- NPM: names are directly derived from npm(the CLI tool)-internals
- Composer: names are directly derived from composer(the CLI tool)-internals

2023-08-24 16:55 UTC, hboutemy commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
> Pipenv and poetry have completely own wordings, definitions, workflows.

same for Maven vs Gradle vs sbt vs ... build tools that use the Maven ecosystem (package sources)

the only difference is that "Maven" term is both an ecosystem and a specific build tool

But I don't see how Pipenv and Poetry have "properties documented [] meant to be implementation-independent, ecosystem-oriented."

For npm, it's not clear if it's "npm the ecosystem", that is for example npmjs.com, or `npm` the build tool only, ignoring how `yarn`, `pnpm`, or other build tools that use the same package do their SBOMs

On Composer, I don't know if there are build tools that are built on top of the ecosystem that the original Composer build tool created


I'm really confused: I don't know if I'm loosing my time trying to create this Maven taxonomy or not
What is clear is that all properties that I'm requiring are specific to Maven the build tool, because other tools use the ecosystem in a different way from a dependency management strategy = what the SBOM is much about

2023-08-24 17:35 UTC, jkowalleck commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
just remove `cdx:maven:package:goal` and all is good.

2023-08-24 22:09 UTC, hboutemy commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
> just remove `cdx:maven:package:goal` and this PR is done.

`cdx:maven:package:optional-unused` is very very `cyclonedx-maven-plugin` specific: then this is the first to be removed also

`cdx:maven:package:scope` is Maven build tool specific: perhaps it's the only one that may make sense in this PR IIUC

2023-08-26 05:14 UTC, jkowalleck commented on cdx/maven.md
> +| `cdx:maven:package:goal` | The goal used to generate the SBOM: `makeBom`, `makeAggregateBom` or `makePackageBom`. May appear once. |
then lets keep the general usable property for now.
if any of the others appear to have a common ground, then they can be added back.
How does this sound?

2023-11-02 15:26 UTC, jkowalleck commented
@hboutemy sorry for my very late reply. 
what is the status of this PR? should it be merged as is? or do you want to add/change something?

2023-11-04 16:50 UTC, hboutemy commented
time passed, re-reading the discussions
it seems the remaining properties from the proposed taxonomy are completely Apache Maven build tool specific, then don't really make any interest to get them shared outside of `cyclonedx-maven-plugin`
i think this PR can be closed now: we extracted the most useful part = `cdx:reproducible`

2023-11-04 16:50 UTC, closed without merging