Add `cdx:rustc` & `cdx:cargo` subnamespaces, take 2
CycloneDX/cyclonedx-property-taxonomy pull request #78
Opened 2023-11-08 22:05 UTC by Shnatsel

fixes https://github.com/CycloneDX/cyclonedx-property-taxonomy/issues/75

Taking over where @lfrancke left off in #77

@jkowalleck I think I've addressed your feedback on the previous iteration of this PR, PTAL.

2023-11-08 22:40 UTC, lfrancke requested changes
Minor issues

2023-11-08 22:40 UTC, lfrancke commented on cdx/rustc.md
> +| `cdx:rustc:meta` | Namespace for information about the SBOM and properties that apply to the entire build. May only appear only in the [`metadata`](https://cyclonedx.org/docs/1.5/json/#metadata_pro
`only` in there twice

2023-11-08 22:40 UTC, lfrancke commented on cdx/rustc.md
> +| `cdx:rustc:meta:target:all_targets` | Indicates that the SBOM includes dependency packages from all possible targets in the [`components`] field, rather than for a single specific target. |
What are the values here? true and false?

2023-11-08 22:54 UTC, lfrancke approved these changes

2023-11-09 10:23 UTC, jkowalleck commented
please redirect your pullrequest into the one brach of @lfrancke - https://github.com/lfrancke/cyclonedx-property-taxonomy/tree/rust 
have your stuff merged

2023-11-09 10:35 UTC, jkowalleck commented on cdx/rustc.md
> +| `cdx:rustc:meta` | Namespace for information about the SBOM and properties that apply to the entire build. May only appear in the [`metadata`](https://cyclonedx.org/docs/1.5/json/#metadata_properti
why in `$.metadata.properties` only? why not allowed in `$.properties`?

2023-11-09 10:35 UTC, jkowalleck commented on cdx/rustc.md
> +| `cdx:rustc:meta:target` | Records the information about the build target for the entire build. |
this should belong to `$.metadata.component.properties`, right? 
but `cdx:rustc:meta` restricts to `$.metadata.properties`

2023-11-09 10:35 UTC, jkowalleck commented on cdx/rustc.md
> +| `cdx:rustc:meta:target:triple` | The target triple used for the build (e.g. `x86_64-unknown-linux-gnu`). Its presence indicates that the list of dependency packages in the [`components`] field will
> in the [`components`] field


instead of linking to the docs, better write:
```md
`$.components`
```

2023-11-09 10:35 UTC, jkowalleck commented on cdx/rustc.md
> +| `cdx:rustc:meta:target:all_targets` | Boolean value. Indicates that the SBOM includes dependency packages from all possible targets in the [`components`] field, rather than for a single specific ta
> Boolean value.

please express which values a "boolean" may have, whether they are case sensitive or not...
see an example: https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/a4638686944651bf92008756602911b02dd4ca07/cdx.md?plain=1#L6-L10

2023-11-09 10:35 UTC, jkowalleck commented on cdx/rustc.md
> +| `cdx:rustc:meta` | Namespace for information about the SBOM and properties that apply to the entire build. May only appear in the [`metadata`](https://cyclonedx.org/docs/1.5/json/#metadata_properti
> May only appear [...]

please uppercase the key words like "MAY", "MUST", "SHOULD".
Please put the declaration on top of your document: https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/a4638686944651bf92008756602911b02dd4ca07/cdx.md?plain=1#L3-L4

2023-11-09 10:48 UTC, jkowalleck commented on cdx/rustc.md
> +| `cdx:rustc:meta:target:triple` | The target triple used for the build (e.g. `x86_64-unknown-linux-gnu`). Its presence indicates that the list of dependency packages in the [`components`] field will
may this property appear only once, or multiple times like
```json5
{ metadata: { component: { properties: [
  {
    name: 'cdx:rustc:meta:target',
    value: 'aarch64-unknown-linux-gnu',
  },
  {
    name: 'cdx:rustc:meta:target',
    value: 'i686-unknown-linux-gnu',
  },
  {
    name: 'cdx:rustc:meta:target',
    value: 'x86_64-unknown-linux-gnu',
  },
]}}}
```

2023-11-09 10:48 UTC, jkowalleck commented on cdx/rustc.md
> +| `cdx:rustc:meta:target:all_targets` | Boolean value. Indicates that the SBOM includes dependency packages from all possible targets in the [`components`] field, rather than for a single specific ta
i suppose this property may appear only once?
could you state this, by adding a note "May appear once."? see an example: https://github.com/CycloneDX/cyclonedx-property-taxonomy/blob/a4638686944651bf92008756602911b02dd4ca07/cdx/npm.md?plain=1#L25

2023-11-09 10:48 UTC, jkowalleck commented on cdx/rustc.md
> +## `cdx:rustc:meta:target` Namespace Taxonomy
from the further reading, i gt the impression, that a CycloneDX document may have only one of { `cdx:rustc:meta:target:triple`, `cdx:rustc:meta:target:all_targets`} , not both at the ame time.
If my impression is true, the this fact should be stated somewhere.

2023-11-28 18:31 UTC, jkowalleck commented
@Shnatsel @lfrancke please see my annotations and questions above.

2023-11-28 18:48 UTC, lfrancke commented
Sorry, we dropped the ball on this. I'll see if I can take a look tomorrow

2023-11-29 19:22 UTC, lfrancke commented on cdx/rustc.md
> +| `cdx:rustc:meta` | Namespace for information about the SBOM and properties that apply to the entire build. May only appear in the [`metadata`](https://cyclonedx.org/docs/1.5/json/#metadata_properti
What's the difference? The docs seem to be the same.

2023-11-29 19:24 UTC, lfrancke commented on cdx/rustc.md
> +| `cdx:rustc:meta:target` | Records the information about the build target for the entire build. |
Good question.
I don't have a good answer to this one. It should go in one place and one place only.
I'm not entirely sure what the best place would be though.

It covers the entire build. All components in the build.

2023-11-29 19:25 UTC, lfrancke commented on cdx/rustc.md
> +## `cdx:rustc:meta:target` Namespace Taxonomy
That is true, yes. (at least I think so)

2024-08-08 11:17 UTC, jkowalleck commented
@Shnatsel could you update this pr?

2024-08-08 11:33 UTC, Shnatsel commented
Sure, I'll take a look in the next few days.

2024-08-08 13:29 UTC, Shnatsel commented on cdx/rustc.md
> +| `cdx:rustc:meta:target` | Records the information about the build target for the entire build. |
No. `$.metadata.component.properties` would refer to the top-level component. This property refers to the SBOM itself.

2024-08-08 13:32 UTC, Shnatsel commented on cdx/rustc.md
> +| `cdx:rustc:meta` | Namespace for information about the SBOM and properties that apply to the entire build. May only appear in the [`metadata`](https://cyclonedx.org/docs/1.5/json/#metadata_properti
Just to define a single specific place where it may appear. I can change it to `$.properties` if you prefer. 

I strongly believe there should only be one single place to specify this, so that consumers of SBOMs do not have to check two different places, and wonder what to do when both places specify a value but disagree on what it is - that would be a constant source of incompatibilities.

2024-08-08 13:43 UTC, Shnatsel commented on cdx/rustc.md
> +| `cdx:rustc:meta:target` | Records the information about the build target for the entire build. |
I'm not sure how that will interact with filling in targets for individual components, which we might want to do later. Let me try to define that and see how that works.

2024-08-08 14:08 UTC, Shnatsel commented on cdx/rustc.md
> +| `cdx:rustc:meta:target` | Records the information about the build target for the entire build. |
`all_targets` on a component would have a different meaning than on the SBOM as a whole. On the SBOM (e.g. in `$.metadata`) it would mean that `$.components` includes packages only used when building for a specific platform. On a component it would mean that the component is depended upon always, without being restricted to a specific list of platforms.

So I've renamed `:meta` to `:sbom` and updated the descriptions to differentiate the two.

2024-08-08 14:25 UTC, Shnatsel commented on cdx/rustc.md
> +| `cdx:rustc:meta` | Namespace for information about the SBOM and properties that apply to the entire build. May only appear in the [`metadata`](https://cyclonedx.org/docs/1.5/json/#metadata_properti
This is already defined at the upper level, in the `cdx` namespace, which we inherit. The terms are used in accordance with RFC2119.

The other `cdx:*` specifications do not include this, and usually do not capitalize their MAYs either, so I will leave this out for consistency and readability. In case anyone actually finds this ambiguous, the definition on these terms of `cdx` should be sufficient.

2024-08-08 14:26 UTC, Shnatsel commented
@jkowalleck I have addressed your feedback, adjusted the names and rewritten the descriptions for clarity. Please take another look.

2024-08-14 10:06 UTC, jkowalleck commented
this looks fantastic. <3

2024-08-14 10:09 UTC, merged